on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
  workflow_dispatch:
    inputs:
      name:
        description: 'ManualRun'

jobs:
  KiCad:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.1
      with:
      # Required - kibot config file
        # config: docs.kibot.yaml
        config: .github/workflows/job/basic.kibot.yaml
        dir: hw/cam
        schema: 'hw/sch_pcb/*.sch'
        board: 'hw/sch_pcb/*.kicad_pcb'
    
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: cam_data
        path: hw/cam
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        message: 'Automation'
        add: 'hw/cam/*.pdf hw/cam/*.svg' 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
